### ISSUE TITLE
readme: link to Gemini client/server?

### ISSUE THREAD

**Issue by derhuerst** [wooorm/dioscuri#1]
Hey, author of [`@derhuerst/gemini`](https://github.com/derhuerst/gemini) here. 👋 

I think for users wanted to interact with the Gemini ecosystem, it's genuinely useful to quickly find a Gemtext parser and a Gemini client/server lib. As both `@derhuerst/gemini` & `dioscuri` are somewhat hard to find with regular search tools, let's cross-link from both readmes.

What do you think?

**Comment by wooorm** [comment]
Excellent idea, added!
