### ISSUE TITLE
Function return values marked as `Node` while README says `Root`

### ISSUE THREAD

**Issue by laosb** [wooorm/dioscuri#4]
For example, in the README [`fromGemtext`](https://github.com/wooorm/dioscuri#fromgemtextdoc-encoding) is marked to return `Root` while [the code](https://github.com/wooorm/dioscuri/blob/main/lib/from-gemtext.js#L24) says it's `Node`. Though casting it to `Root` works, is there any reason for doing so?

**Comment by wooorm** [comment]
I don’t have strong opinions on this. I’m fine with using `Node` in the docs, that would make the align the method that does the inverse (`toGemtext`) better with `fromGemtext`.

**Comment by laosb** [comment]
To me it sounds using `Root` would be more accurate, and for TS users they'll need to manually cast to `Root` (like `const result = fromGemtext(gemtext) as Root`), which is probably unnecessary. I'd vote for changing the code to align with the accurate doc markup.

**Comment by wooorm** [comment]
Why do you need to cast to root?
Similar to `toGemtext`, which accepts any node, where you’re using it could also handle different node types?

**Comment by wooorm** [comment]
I now think you’re quite right that a root would make more sense. Is that something you could help with?

**Comment by wooorm** [comment]
Solved!
