### ISSUE TITLE
A line with a single link in markdown is still formatted as a footnote in gemtext

### ISSUE THREAD

**Issue by Tryops** [wooorm/dioscuri#5]
[A quick introduction to "gemtext" markup](https://gemini.circumlunar.space/docs/gemtext.gmi) says that gemtext can only contain one link per line (which makes sense). 
I think it's really smart to then format inline links from markdown as footnotes in gemtext. But is it also intended that one link per line in markdown gets also formatted as a footnote in gemtext instead of one link per line in gemtext? 
Or do I miss something?

Example:
```js
(async () => {
const { toGemtext, fromMdast } = await import('dioscuri');
const mdast = await import('mdast-util-from-markdown');

const markdown = 
`# Title
This [link](http://example.com) is formatted as a footnote.
Should the following link also be a footnote?

[Another link](http://placekitten.com/)`;

const tree = mdast.fromMarkdown(markdown);
const gemtext= toGemtext(fromMdast(tree));
console.log(gemtext);
})();
```
Result:

```gemtext
This link[1] is formatted as a footnote. Should the following link also be a footnote?

Another link[2]

=> http://example.com [1]

=> http://placekitten.com/ [2]
```

**Comment by wooorm** [comment]
How else should they appear?

**Comment by Tryops** [comment]
As far as I understand like this:

```gemtext
This link[1] is formatted as a footnote. Should the following link also be a footnote?

=> http://placekitten.com/ Another link

=> http://example.com [1]
```
"link[1]" still needs the footnote because it is inline in markdown (which gemtext doesn't support). 

"Another link" doesn't need a footnote because it can be a link on its own. It has an entire line in markdown and an entire line in gemtext after the parsing so it could be a link in gemtext directly.

**Comment by wooorm** [comment]
But that would change the order though.
And, isn't a paragraph with only a link a bit weird?

**Comment by Tryops** [comment]
Yeah it would change the order of the footnotes and I agree that in plain text a paragraph with only one link does look wierd (when not using a proper gemini client or proxy though). 
But only having footnotes as links makes it impossible to have lists of links and nav sections for example (which is what I'm trying to do). 

Something like the list of links [on this gemini page](https://portal.mozz.us/gemini/midnight.pub/posts) ([gemtext source](https://portal.mozz.us/gemini/midnight.pub/posts?raw=1)) which are easily possible in markdown (as just one markdown link per line) would not be possible when only having footnotes as links in gemtext when parsing that markdown.

**Comment by wooorm** [comment]
Hmm.

What is the actual text you have? Where did you actually run into this problem?

While the link you gave to the list of posts is an interesting example, I’m thinking it would in that case be smarter to generate a list of gemtext nodes with code instead of manually writing the list in markdown and then converting it to gemtext?

**Comment by wooorm** [comment]
Friendly ping!

**Comment by Tryops** [comment]
Sorry it's been so long. 
> What is the actual text you have? Where did you actually run into this problem?

Just when parsing posts from a small blog formatted as markdown that should be mirrored on a gemini page. I thought it would be convenient if you could switch between footnote mode and inline link mode or something. Not really important but I thought it would be nice if there was a parser that could do that. 

> While the link you gave to the list of posts is an interesting example, I’m thinking it would in that case be smarter to generate a list of gemtext nodes with code instead of manually writing the list in markdown and then converting it to gemtext?

Thats what I did partially (generating links to posts, like in the example) but I was just concerned with really having a list of links in my markdown and wanting to have that same list on the same place in my gemtext. 

For example when I refer to other pages in a post like so: 
```markdown
These are some good web code editors:
[Monaco](https://microsoft.github.io/monaco-editor/)
[Ace](https://ace.c9.io/)
[CodeMirror](https://codemirror.net/)
```
The gemtext could look like this after parsing, which would be cool:
```markdown
These are some good web code editors:
=> https://microsoft.github.io/monaco-editor/ Monaco
=> https://ace.c9.io/ Ace
=> https://codemirror.net/ CodeMirror
```
And both outputs would look the same on web and gemini: 

> These are some good web code editors:
[Monaco](https://microsoft.github.io/monaco-editor/)
[Ace](https://ace.c9.io/)
[CodeMirror](https://codemirror.net/)

I don't really know how mdast or this parser works so thats why I asked, but its not really important.

**Comment by Tryops** [comment]
Ok this is my solution now: 

```js
let md = 
`These are some good web code editors:
[Monaco](https://microsoft.github.io/monaco-editor/)
[Ace](https://ace.c9.io/)
[CodeMirror](https://codemirror.net/)`;

 // replace single line markdown links with gemtext links before parsing:
md = md.replace(/^\[([^\[\]]*)\]\(([^\(\)]*)\)\s*$/gm, '=> $2 $1\n');

// continue parsing md
```
Ok wow I didn't think about that before, sorry.
