### ISSUE TITLE
Firefox extension

### ISSUE THREAD

**Issue by vinipsmaker** [wooorm/dioscuri#6]
It'd be nice if there was a Firefox extension to preview/render Gemtext in Firefox. For instance, something like this (but for Gemtext): https://addons.mozilla.org/en-US/firefox/addon/asciidoctorjs-live-preview/

**Comment by wooorm** [comment]
Sure, feel free to make one.
It’s a much higher abstraction than ASTs and compilers though, which is what this project does.
