### ISSUE TITLE
Conversion to mdast: breaks should be converted too

### ISSUE THREAD

**Issue by BubuAnabelas** [wooorm/dioscuri#7]
Currently breaks are discarded when converting a Gast into a Mdast, instead they should be converted into [mdast's Breaks](https://github.com/syntax-tree/mdast#break)

The function that should be converting breaks is a noop:
https://github.com/wooorm/dioscuri/blob/3b5ec0a396f790d85ac9405b6d0a710e72f038c1/lib/to-mdast.js#L76

**Comment by wooorm** [comment]
markdown breaks are only allowed in phrasing (e.g., just like emphasis). Gem text breaks are only allowed in flow (e.g., just like headings). So it can't really map

**Comment by BubuAnabelas** [comment]
You are right, I was getting and unexpected behavior because I was using some of the function's all wrong.

Great lib thanks for the good foss work! :sparkling_heart:
